work_dir: ./work_dir/pdmb/mymodel_withself/reduceothers2trainv32_withinterTrue_nodrop_module3re_reladegree_tmm/
model_saved_name: ./runs/pdmb/mymodel_withself/reduceothers2trainv32_withinterTrue_nodrop_module3re_reladegree_tmm/
#work_dir: ./work_dir/pdmb/mymodel_withself/reduceothers2trainv3_withinterTrue_nodrop_module3re2_BCM/
#model_saved_name: ./runs/pdmb/mymodel_withself/reduceothers2trainv3_withinterTrue_nodrop_module3re2_BCM/
#work_dir: ./work_dir/pdmb/mymodel_withself/reduceothers3trainv2/
#model_saved_name: ./runs/pdmb/mymodel_withself/reduceothers3trainv2/
#split_train: /scratch/3dpoint/fz64/dataset/PDMB/splits/trainfile_debug.txt
#split_test: /scratch/3dpoint/fz64/dataset/PDMB/splits/testfile_debug.txt
split_train: /scratch/3dpoint/fz64/dataset/PDMB/splits/trainfilev3.txt
split_test: /scratch/3dpoint/fz64/dataset/PDMB/splits/testfilev3.txt

#multi-video
numclass: 9
sample_rate: 1
features_path: /scratch/3dpoint/fz64/dataset/PDMB/data_withothers_center_reduceothers2/
gt_path: /scratch/3dpoint/fz64/dataset/PDMB/data_withothers_center_reduceothers2/
#features_path: /scratch/3dpoint/fz64/dataset/PDMB/data_noothers_center/
#gt_path: /scratch/3dpoint/fz64/dataset/PDMB/data_noothers_center/
#features_path: /scratch/3dpoint/fz64/dataset/PDMB/data_noothers_center_splitvideo/
#gt_path: /scratch/3dpoint/fz64/dataset/PDMB/data_noothers_center_splitvideo/


# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 40
  data_path: /scratch/3dpoint/fz64/dataset/PDMB/data_withothers_center/video213_1_data_joint.npy
  label_path: /scratch/3dpoint/fz64/dataset/PDMB/data_withothers_center/video213_1_data_joint.pkl
  debug: False

test_feeder_args:
  data_path: /scratch/3dpoint/fz64/dataset/PDMB/data_withothers_center/video213_1_data_joint.npy
  label_path: /scratch/3dpoint/fz64/dataset/PDMB/data_withothers_center/video213_1_data_joint.pkl
  random_choose: True
  window_size: 40

# model
model: model.agcn_multiskeleton_withself.Model
model_args:
  num_class: 9
  num_person: 2
  num_point: 7
  graph: graphori.crim13.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.0005
step: [50, 200]


# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 150
nesterov: True






