split_train: /scratch/3dpoint/fz64/dataset/CRIM13/splits/trainfilev5.txt
#split_test: /scratch/3dpoint/fz64/dataset/CRIM13/splits/testfilev2.txt
#split_test: /scratch/3dpoint/fz64/dataset/CRIM13/splits/testfilev2.txt
split_test: /scratch/3dpoint/fz64/dataset/CRIM13/splits/testfilev2_matrix.txt
#split_test: /scratch/3dpoint/fz64/dataset/CRIM13/splits/testfilev2_video162.txt

#multi-video
numclass: 12
sample_rate: 1
features_path: /scratch/3dpoint/fz64/dataset/CRIM13/data_withothers_center_reduceothers3/
gt_path: /scratch/3dpoint/fz64/dataset/CRIM13/data_withothers_center_reduceothers3/
#features_path: /scratch/3dpoint/fz64/dataset/CRIM13/data_noothers_center/
#gt_path: /scratch/3dpoint/fz64/dataset/CRIM13/data_noothers_center/
#features_path: /scratch/3dpoint/fz64/dataset/CRIM13/data_noothers_center_splitvideo/
#gt_path: /scratch/3dpoint/fz64/dataset/CRIM13/data_noothers_center_splitvideo/

# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: /scratch/3dpoint/fz64/dataset/CRIM13/data_withothers_center_reduceothers3/Tvideo_0_data_joint.npy
  label_path: /scratch/3dpoint/fz64/dataset/CRIM13/data_withothers_center_reduceothers3/Tvideo_0_data_joint.pkl
  random_choose: True
  window_size: 40
  debug: False

# model 
# model: model.agcn.Model
model: model.agcn_multiskeleton_withself.Model
model_args:
  num_class: 12
  num_person: 2
  num_point: 7
  graph: graphori.crim13.Graph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: test
device: [0, 1]
test_batch_size: 128
weights: null


#work_dir: ./work_dir/crim13/mymodel_withself/reduceothers3trainv5_withinterTrue_layer4module3re_tmm_BCM/testresult/
#model_saved_name: ./runs/crim13/mymodel_withself/reduceothers3trainv5_withinterTrue_layer4module3re_tmm_BCM/
work_dir: ./work_dir/crim13/mymodel_withself/reduceothers3trainv5_withinterTrue_layer4module3re_reladegree_tmm/testresult/
model_saved_name: ./runs/crim13/mymodel_withself/reduceothers3trainv5_withinterTrue_layer4module3re_reladegree_tmm/
save_score: True